"""Versioned, interpretation-free classical natal facts."""

from .dignities import dignity_rulers_at, evaluate_essential_dignity
from .dispositors import calculate_traditional_dispositors
from .lots import calculate_fortune_and_spirit, calculate_supported_lots
from .models import (
    DignityCondition,
    DignityKind,
    DispositorEdge,
    DispositorGraphResult,
    EssentialDignityResult,
    EssentialStatusFact,
    EssentialStatusLevel,
    EssentialStatusPolarity,
    HouseRulerAssignment,
    LotId,
    LotOperand,
    LotResult,
    MutualReception,
    Reception,
    ReceptionResult,
    Sect,
    SectResult,
    SolarConditionResult,
    SolarRelation,
    SolarThresholdProfile,
    TableReference,
    TriplicityRole,
)
from .receptions import calculate_receptions
from .rulership import assign_house_rulers, modern_rulers, traditional_rulers
from .sect import require_sect, sect_facts
from .solar import LILLY_SOLAR_THRESHOLDS_V1, classify_solar_condition
from .tables import (
    CHALDEAN_FACE_RULERS,
    CHALDEAN_FACES_TABLE_REF,
    DOROTHEAN_TRIPLICITIES,
    DOROTHEAN_TRIPLICITY_TABLE_REF,
    EGYPTIAN_TERMS,
    EGYPTIAN_TERMS_TABLE_REF,
    EXALTATION_RULER_BY_SIGN,
    EXALTATION_TABLE_REF,
    MODERN_RULERS_BY_SIGN,
    MODERN_RULERSHIP_TABLE_REF,
    TRADITIONAL_PLANET_IDS,
    TRADITIONAL_RULERS_BY_SIGN,
    TRADITIONAL_RULERSHIP_TABLE_REF,
    face_ruler,
    sign_and_degree,
    term_ruler,
)

__all__ = [
    "CHALDEAN_FACE_RULERS",
    "CHALDEAN_FACES_TABLE_REF",
    "DOROTHEAN_TRIPLICITIES",
    "DOROTHEAN_TRIPLICITY_TABLE_REF",
    "DignityCondition",
    "DignityKind",
    "DispositorEdge",
    "DispositorGraphResult",
    "EGYPTIAN_TERMS",
    "EGYPTIAN_TERMS_TABLE_REF",
    "EXALTATION_RULER_BY_SIGN",
    "EXALTATION_TABLE_REF",
    "EssentialDignityResult",
    "EssentialStatusFact",
    "EssentialStatusLevel",
    "EssentialStatusPolarity",
    "HouseRulerAssignment",
    "LILLY_SOLAR_THRESHOLDS_V1",
    "LotId",
    "LotOperand",
    "LotResult",
    "MODERN_RULERS_BY_SIGN",
    "MODERN_RULERSHIP_TABLE_REF",
    "MutualReception",
    "Reception",
    "ReceptionResult",
    "Sect",
    "SectResult",
    "SolarConditionResult",
    "SolarRelation",
    "SolarThresholdProfile",
    "TRADITIONAL_PLANET_IDS",
    "TRADITIONAL_RULERS_BY_SIGN",
    "TRADITIONAL_RULERSHIP_TABLE_REF",
    "TableReference",
    "TriplicityRole",
    "assign_house_rulers",
    "calculate_fortune_and_spirit",
    "calculate_supported_lots",
    "calculate_receptions",
    "calculate_traditional_dispositors",
    "classify_solar_condition",
    "dignity_rulers_at",
    "evaluate_essential_dignity",
    "face_ruler",
    "modern_rulers",
    "require_sect",
    "sect_facts",
    "sign_and_degree",
    "term_ruler",
    "traditional_rulers",
]
