"""Stable source, rule, and algorithm identifiers for classical facts."""

ALG_DIGNITY_RECEPTION = "ALG-NATAL-004"
ALG_ARABIC_PARTS = "ALG-NATAL-005"

PROFILE_TRADITIONAL_ESSENTIAL_V1 = "classical.essential.traditional_seven.v1"

SRC_PTOLEMY_TETRABIBLOS = "source.ptolemy.tetrabiblos"
SRC_DOROTHEUS_CARMEN = "source.dorotheus.carmen_astrologicum"
SRC_LILLY_CHRISTIAN_ASTROLOGY = "source.lilly.christian_astrology.1647"
SRC_PAULUS_INTRODUCTORY_MATTERS = "source.paulus.introductory_matters"
SRC_ROBERT_HAND_LOT_OF_BASIS = "source.robert_hand.lot_or_part_of_fortune"
SRC_INTERSTELLAR_MODERN_RULERSHIP_PROFILE = "source.interstellar.modern_rulership_profile.v1"

RULE_SECT_EXPLICIT_V1 = "classical.sect.explicit.v1"
RULE_TRADITIONAL_RULERSHIP_V1 = "classical.rulership.traditional_seven.v1"
RULE_MODERN_RULERSHIP_V1 = "classical.rulership.modern_corulers.v1"
RULE_ESSENTIAL_EXALTATION_V1 = "classical.exaltation.ptolemaic.v1"
RULE_DETRIMENT_V1 = "classical.detriment.opposite_domicile.v1"
RULE_FALL_V1 = "classical.fall.opposite_exaltation.v1"
RULE_TRIPLICITY_DOROTHEAN_V1 = "classical.triplicity.dorothean.v1"
RULE_TRIPLICITY_PTOLEMAIC_V1 = "classical.triplicity.ptolemaic.v1"
RULE_TERMS_EGYPTIAN_V1 = "classical.terms.egyptian.v1"
RULE_TERMS_PTOLEMAIC_V1 = "classical.terms.ptolemaic.v1"
# Compatibility aliases for callers which intentionally use the default tables.
RULE_TRIPLICITY_V1 = RULE_TRIPLICITY_DOROTHEAN_V1
RULE_TERMS_V1 = RULE_TERMS_EGYPTIAN_V1
RULE_FACES_V1 = "classical.faces.chaldean.v1"
RULE_PEREGRINE_V1 = "classical.peregrine.no_positive_essential_dignity.v1"
RULE_DISPOSITOR_V1 = "classical.dispositor.traditional_domicile.v1"
RULE_RECEPTION_V1 = "classical.reception.dignity_without_aspect.v1"
RULE_MUTUAL_RECEPTION_V1 = "classical.reception.mutual_pair.v1"
RULE_SOLAR_CONDITION_V1 = "classical.solar_condition.lilly_thresholds.v1"
RULE_FORTUNE_V1 = "classical.lot.fortune.paulus.v1"
RULE_SPIRIT_V1 = "classical.lot.spirit.paulus.v1"
RULE_BASIS_V1 = "classical.lot.basis.hand_shorter_arc.v1"
RULE_EROS_V1 = "classical.lot.eros.paulus.v1"
RULE_NECESSITY_V1 = "classical.lot.necessity.paulus.v1"
RULE_COURAGE_V1 = "classical.lot.courage.paulus.v1"
RULE_VICTORY_V1 = "classical.lot.victory.paulus.v1"
RULE_NEMESIS_V1 = "classical.lot.nemesis.paulus.v1"
RULE_LOT_EXALTATION_V1 = "classical.lot.exaltation.paulus.v1"
