#!/usr/bin/env python3
"""Generate deterministic, dependency-free contract index types.

These files are intentionally *index types*, not a replacement for JSON Schema
validation. They provide stable document/definition/operation names until a pinned
full OpenAPI generator is adopted. Source schemas and OpenAPI remain authoritative.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from validate_openapi import (
    DEFAULT_OPENAPI,
    DEFAULT_SCHEMA_DIR,
    HTTP_METHODS,
    REPO_ROOT,
    load_json,
    load_yaml,
    validate_all,
)


DEFAULT_OUTPUT_DIR = DEFAULT_SCHEMA_DIR / "generated"


@dataclass(frozen=True)
class ContractDocument:
    file_name: str
    schema_id: str
    title: str
    definitions: tuple[str, ...]
    sha256: str


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _identifier(value: str, fallback: str = "Contract") -> str:
    parts = re.findall(r"[A-Za-z0-9]+", value)
    candidate = "".join(part[:1].upper() + part[1:] for part in parts) or fallback
    if candidate[0].isdigit():
        candidate = f"_{candidate}"
    return candidate


def collect_contracts(schema_dir: Path) -> list[ContractDocument]:
    contracts: list[ContractDocument] = []
    for path in sorted(schema_dir.glob("*.schema.json"), key=lambda item: item.name):
        document = load_json(path)
        contracts.append(
            ContractDocument(
                file_name=path.name,
                schema_id=document["$id"],
                title=document.get("title", path.stem),
                definitions=tuple(sorted(document.get("$defs", {}).keys())),
                sha256=_sha256(path),
            )
        )
    return contracts


def collect_operations(openapi_path: Path) -> list[str]:
    document = load_yaml(openapi_path)
    operations: list[str] = []
    for path_name in sorted(document["paths"]):
        path_item = document["paths"][path_name]
        for method in sorted(HTTP_METHODS):
            operation = path_item.get(method)
            if isinstance(operation, dict) and isinstance(operation.get("operationId"), str):
                operations.append(operation["operationId"])
    return sorted(operations)


def render_typescript(contracts: list[ContractDocument], operations: list[str]) -> str:
    lines = [
        "/* AUTO-GENERATED by scripts/generate_contract_types.py. DO NOT EDIT. */",
        "/* Stable index types only; validate payloads against the source JSON Schemas. */",
        "",
        "export type JsonPrimitive = null | boolean | number | string;",
        "export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };",
        "export type JsonObject = { [key: string]: JsonValue };",
        "",
        "export interface ContractDescriptor {",
        "  readonly schemaId: string;",
        "  readonly title: string;",
        "  readonly definitions: readonly string[];",
        "  readonly sha256: string;",
        "}",
        "",
        "export const CANONICAL_CONTRACTS = {",
    ]
    for contract in contracts:
        definitions = ", ".join(json.dumps(item) for item in contract.definitions)
        lines.extend(
            [
                f"  {json.dumps(contract.file_name)}: {{",
                f"    schemaId: {json.dumps(contract.schema_id)},",
                f"    title: {json.dumps(contract.title)},",
                f"    definitions: [{definitions}],",
                f"    sha256: {json.dumps(contract.sha256)},",
                "  },",
            ]
        )
    lines.extend(
        [
            "} as const satisfies Record<string, ContractDescriptor>;",
            "",
            "export type SchemaDocumentName = keyof typeof CANONICAL_CONTRACTS;",
            "",
        ]
    )
    for contract in contracts:
        prefix = _identifier(Path(contract.file_name).name.replace(".schema.json", ""))
        lines.append(f"export type {prefix}Document = JsonObject;")
        for definition in contract.definitions:
            lines.append(f"export type {prefix}{_identifier(definition)} = JsonObject;")
        lines.append("")
    lines.append("export const API_OPERATION_IDS = [")
    lines.extend(f"  {json.dumps(operation)}," for operation in operations)
    lines.extend(
        [
            "] as const;",
            "",
            "export type ApiOperationId = (typeof API_OPERATION_IDS)[number];",
            "",
        ]
    )
    return "\n".join(lines)


def render_python(contracts: list[ContractDocument], operations: list[str]) -> str:
    operation_literal = ", ".join(repr(operation) for operation in operations)
    lines = [
        '"""AUTO-GENERATED stable contract index types. DO NOT EDIT.',
        "",
        "Payload validation remains the responsibility of the source JSON Schemas.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Final, Literal, TypeAlias, TypedDict",
        "",
        "JSONPrimitive: TypeAlias = None | bool | int | float | str",
        'JSONValue: TypeAlias = JSONPrimitive | list["JSONValue"] | dict[str, "JSONValue"]',
        "JSONObject: TypeAlias = dict[str, JSONValue]",
        "",
        "class ContractDescriptor(TypedDict):",
        "    schema_id: str",
        "    title: str",
        "    definitions: tuple[str, ...]",
        "    sha256: str",
        "",
        "CANONICAL_CONTRACTS: Final[dict[str, ContractDescriptor]] = {",
    ]
    for contract in contracts:
        lines.extend(
            [
                f"    {contract.file_name!r}: {{",
                f"        'schema_id': {contract.schema_id!r},",
                f"        'title': {contract.title!r},",
                f"        'definitions': {contract.definitions!r},",
                f"        'sha256': {contract.sha256!r},",
                "    },",
            ]
        )
    lines.extend(["}", ""])
    for contract in contracts:
        prefix = _identifier(Path(contract.file_name).name.replace(".schema.json", ""))
        lines.append(f"{prefix}Document: TypeAlias = JSONObject")
        for definition in contract.definitions:
            lines.append(f"{prefix}{_identifier(definition)}: TypeAlias = JSONObject")
    lines.extend(
        [
            "",
            f"ApiOperationId: TypeAlias = Literal[{operation_literal}]",
            "API_OPERATION_IDS: Final[tuple[ApiOperationId, ...]] = (",
        ]
    )
    lines.extend(f"    {operation!r}," for operation in operations)
    lines.extend([")", ""])
    return "\n".join(lines)


def render_manifest(
    contracts: list[ContractDocument], operations: list[str], openapi_path: Path
) -> str:
    document: dict[str, Any] = {
        "generator": "scripts/generate_contract_types.py",
        "format_version": 1,
        "source_of_truth": {
            "openapi": str(openapi_path.relative_to(REPO_ROOT)),
            "openapi_sha256": _sha256(openapi_path),
            "schema_directory": str(DEFAULT_SCHEMA_DIR.relative_to(REPO_ROOT)),
        },
        "schemas": [
            {
                "file": contract.file_name,
                "schema_id": contract.schema_id,
                "title": contract.title,
                "definitions": list(contract.definitions),
                "sha256": contract.sha256,
            }
            for contract in contracts
        ],
        "operation_ids": operations,
    }
    return json.dumps(document, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def expected_outputs(
    schema_dir: Path, openapi_path: Path
) -> dict[str, str]:
    contracts = collect_contracts(schema_dir)
    operations = collect_operations(openapi_path)
    return {
        "types.ts": render_typescript(contracts, operations),
        "types.py": render_python(contracts, operations),
        # A non-.json suffix prevents generic Schema discovery from mistaking this
        # provenance document for another Canonical JSON Schema.
        "manifest.lock": render_manifest(contracts, operations, openapi_path),
    }


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--openapi", type=Path, default=DEFAULT_OPENAPI)
    parser.add_argument("--schema-dir", type=Path, default=DEFAULT_SCHEMA_DIR)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; fail when committed generated files differ.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    openapi_path = args.openapi.resolve()
    schema_dir = args.schema_dir.resolve()
    output_dir = args.output_dir.resolve()
    validate_all(openapi_path, schema_dir, REPO_ROOT)
    outputs = expected_outputs(schema_dir, openapi_path)

    if args.check:
        stale: list[str] = []
        for name, content in outputs.items():
            path = output_dir / name
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(REPO_ROOT)))
        if stale:
            print("Generated contract files are missing or stale:", file=sys.stderr)
            for path in stale:
                print(f"- {path}", file=sys.stderr)
            print("Run: python3 scripts/generate_contract_types.py", file=sys.stderr)
            return 1
        print(f"Generated contract check passed: {len(outputs)} files are deterministic.")
        return 0

    output_dir.mkdir(parents=True, exist_ok=True)
    for name, content in outputs.items():
        (output_dir / name).write_text(content, encoding="utf-8")
    print(
        f"Generated {len(outputs)} contract files for "
        f"{len(collect_contracts(schema_dir))} schemas and "
        f"{len(collect_operations(openapi_path))} API operations."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
