package main

import (
	"html/template"
	"net/http"
	"strings"
)

type legalCopy struct {
	Language string
	Title    string
	Updated  string
	Body     template.HTML
}

var privacyCopies = []legalCopy{
	{"English", "Privacy Policy", "Updated 22 August 2026", `<p>Interstellar performs astrological calculations on your device. ChatGPT does not calculate charts or provide the app's fixed chart content; it only helps refine a report when you request one. The name or nickname, relationship type when applicable, and calculated chart results are sent through Interstellar Relay to ChatGPT, provided by OpenAI. Your profile birth date, birth time and birthplace are not sent. You can use a nickname if you prefer.</p><p>Relay retains an anonymous User ID, a hashed installation link and App Attest records, subscription and purchase records, Credit and report-delivery records, and limited service-usage metadata. Submitted names and calculated results are used only to service the request and are not retained by Relay. The generated report is stored encrypted only until the device saves it and acknowledges delivery; Relay then deletes it and no longer stores it. ChatGPT processes the request under OpenAI's privacy terms.</p><p>If you enable iCloud Backup, profiles, reports and settings are stored in your private iCloud container. Delete account and data in Account settings removes local and iCloud personal data, report-delivery metadata, and all usable Credits, then creates a new empty User ID. The inactive User ID, its successor relationship, and purchase, subscription, and Credit financial history remain in Relay for accounting, subscription restoration, and duplicate-Credit prevention.</p>`},
	{"简体中文", "隐私政策", "更新于 2026 年 8 月 22 日", `<p>Interstellar 在设备本地完成占星计算。ChatGPT 不计算星盘，也不生成 App 内固定星盘内容；只有你主动请求报告时，ChatGPT 才辅助优化报告。名字或昵称、适用时的关系类型及已计算星盘结果会经 Interstellar Relay 发送给 OpenAI 提供的 ChatGPT。不会发送 Profile 中的出生日期、出生时间和出生地点；如担心姓名泄露，可以使用昵称。</p><p>Relay 会保留匿名 User ID、经过哈希的安装关联与 App Attest 记录、订阅与购买记录、Credit 与报告交付记录，以及有限的服务使用元数据。提交的名字和计算结果仅用于处理该次请求，Relay 不会持续保留。生成的报告只会加密暂存至本机保存并确认交付；确认后 Relay 会立即删除且不再保存。ChatGPT 按 OpenAI 的隐私条款处理该请求。</p><p>如果启用 iCloud 备份，人物、报告和设置会保存到私人 iCloud 容器。在账户设置中删除账户与数据会清除本机和 iCloud 个人数据、报告交付元数据及所有可用 Credits，并创建新的空 User ID。停用的 User ID、后继关联以及购买、订阅和 Credit 财务历史会保留在 Relay，用于财务记录、恢复订阅和防止重复领取 Credits。</p>`},
	{"Español", "Política de privacidad", "Actualizada el 22 de agosto de 2026", `<p>Interstellar realiza los cálculos astrológicos en el dispositivo. ChatGPT no calcula cartas ni proporciona el contenido fijo de la app; solo ayuda a perfeccionar un informe cuando lo solicitas. El nombre o apodo, el tipo de relación cuando corresponda y los resultados calculados se envían a ChatGPT, proporcionado por OpenAI, mediante Interstellar Relay. No se envían la fecha, hora ni lugar de nacimiento del perfil. Puedes usar un apodo.</p><p>Relay conserva un User ID anónimo, una vinculación de instalación con hash y registros de App Attest, suscripciones y compras, Credits, entrega de informes y metadatos limitados de uso. Los nombres y resultados enviados se usan solo para atender la solicitud y Relay no los conserva. El informe se almacena cifrado solo hasta que el dispositivo lo guarda y confirma la entrega; después Relay lo elimina y deja de conservarlo. ChatGPT procesa la solicitud conforme a las condiciones de privacidad de OpenAI.</p><p>Eliminar cuenta y datos borra los datos personales locales y de iCloud, los metadatos de entrega y todos los Credits utilizables, y crea un User ID nuevo y vacío. El User ID inactivo, su relación sucesora y el historial financiero de compras, suscripciones y Credits permanecen en Relay para contabilidad, restauración y prevención de duplicados.</p>`},
	{"Français", "Politique de confidentialité", "Mise à jour le 22 août 2026", `<p>Interstellar effectue les calculs astrologiques sur l'appareil. ChatGPT ne calcule pas les thèmes et ne fournit pas le contenu fixe de l'app ; il aide uniquement à améliorer un rapport lorsque vous le demandez. Le nom ou surnom, le type de relation le cas échéant et les résultats calculés sont envoyés à ChatGPT, fourni par OpenAI, via Interstellar Relay. La date, l'heure et le lieu de naissance du profil ne sont pas envoyés. Vous pouvez utiliser un surnom.</p><p>Relay conserve un User ID anonyme, un lien d'installation haché et les données App Attest, les abonnements et achats, les Credits, la livraison des rapports et des métadonnées limitées d'utilisation. Les noms et résultats soumis servent uniquement à traiter la demande et ne sont pas conservés par Relay. Le rapport est stocké chiffré jusqu'à son enregistrement et à l'accusé de réception de cet appareil ; Relay le supprime ensuite et ne le conserve plus. ChatGPT traite la demande conformément aux conditions de confidentialité d'OpenAI.</p><p>Supprimer le compte et les données efface les données personnelles locales et iCloud, les métadonnées de livraison et tous les Credits utilisables, puis crée un nouvel User ID vide. L'User ID désactivé, sa relation de succession et l'historique financier des achats, abonnements et Credits restent dans Relay pour la comptabilité, la restauration et la prévention des doublons.</p>`},
}

var termsCopies = []legalCopy{
	{"English", "Terms of Use", "Updated 12 August 2026", `<p>Interstellar provides astrological calculations and interpretive content for personal reflection and entertainment. It is not medical, legal, financial or emergency advice.</p><p>Premium Monthly and Premium Annual renew automatically unless cancelled in your Apple account settings. Purchased Credits are consumable and do not expire. Free or Premium allowance Credits refill according to the plan and unused allowance may be replaced at the next refill.</p><p>An AI report consumes one Credit only after it passes validation, is saved locally and the app acknowledges delivery. If delivery is not acknowledged, the reservation is released. Purchases and subscriptions are also governed by Apple’s Standard EULA.</p>`},
	{"简体中文", "使用条款", "更新于 2026 年 8 月 12 日", `<p>Interstellar 提供占星计算和解读内容，用于个人思考与娱乐，不构成医疗、法律、财务或紧急建议。</p><p>Premium 月度和年度订阅会自动续订，除非你在 Apple 账户设置中取消。购买的 Credits 属于消耗型项目且永久有效；免费或 Premium 配额按方案补充，未使用的配额可能在下一周期被替换。</p><p>AI 报告只有在通过验证、成功保存到本地并由 App 确认交付后才消费 1 Credit；未确认交付则释放预留。购买和订阅同时受 Apple 标准最终用户许可协议约束。</p>`},
	{"Español", "Términos de uso", "Actualizados el 12 de agosto de 2026", `<p>Interstellar ofrece cálculos astrológicos y contenido interpretativo para reflexión personal y entretenimiento. No constituye asesoramiento médico, jurídico, financiero ni de emergencia.</p><p>Premium Mensual y Anual se renuevan automáticamente salvo cancelación en los ajustes de la cuenta Apple. Los Credits comprados son consumibles y no caducan; los Credits de asignación se renuevan según el plan.</p><p>Un informe de IA consume un Credit solo tras validarse, guardarse localmente y confirmarse la entrega. Sin confirmación, la reserva se libera. También se aplica el EULA estándar de Apple.</p>`},
	{"Français", "Conditions d’utilisation", "Mises à jour le 12 août 2026", `<p>Interstellar fournit des calculs astrologiques et des interprétations à des fins de réflexion personnelle et de divertissement. Il ne s’agit pas d’un conseil médical, juridique, financier ou d’urgence.</p><p>Premium mensuel et annuel se renouvellent automatiquement sauf annulation dans les réglages du compte Apple. Les Credits achetés sont consommables et n’expirent pas ; les Credits d’allocation sont renouvelés selon l’offre.</p><p>Un rapport IA consomme un Credit uniquement après validation, enregistrement local et confirmation de livraison. Sans confirmation, la réservation est libérée. Le contrat de licence standard Apple s’applique également.</p>`},
}

func handleLegalPage(w http.ResponseWriter, r *http.Request) {
	copies := privacyCopies
	if strings.HasPrefix(r.URL.Path, "/terms") {
		copies = termsCopies
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("Cache-Control", "public, max-age=3600")
	_, _ = w.Write([]byte(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Interstellar</title><style>body{max-width:760px;margin:40px auto;padding:0 20px;background:#0b0d16;color:#f2f2f7;font:16px/1.65 system-ui}section{padding:20px 0;border-bottom:1px solid #2b3042}h1{margin-bottom:4px}small{color:#9ea5bb}a{color:#a98bff}</style></head><body>`))
	for _, copy := range copies {
		_, _ = w.Write([]byte("<section><small>" + template.HTMLEscapeString(copy.Language) + "</small><h1>" + template.HTMLEscapeString(copy.Title) + "</h1><small>" + template.HTMLEscapeString(copy.Updated) + "</small>" + string(copy.Body) + "</section>"))
	}
	_, _ = w.Write([]byte(`<p><a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/">Apple Standard EULA</a></p></body></html>`))
}
